#!/usr/bin/env python3
"""
LVS V6: Generate named-pin hierarchical SPICE for layout and schematic,
        then invoke Netgen LVS with -blackbox mode.

Strategy:
  - Reuse parse_def / parse_verilog from lvs.py to get canonical parsed
    connectivity (already 0-error matched).
  - Drop physical-only cells (FILLER*, TAP*, DIODE*, ANTENNA*, DECAP*, *_DEF_FILL, VIA_*).
  - For every remaining logic cell, if DEF/Verilog pin-connection misses
    VPWR/VGND/VNB/VPB (they are implicit global P/G in DEF SPECIALNETS),
    AUGMENT with explicit connections:
        VPWR -> net "VPWR"
        VGND -> net "VGND"
        VNB  -> net "VGND"   (N-well substrate tied to GND in sky130)
        VPB  -> net "VPWR"   (P-well substrate tied to VPWR in sky130)
  - Write two SPICE files in NETGEN-compatible named-pin format:
        .SUBCKT SHA256  clk rst soc rd eoc data[0] ... data[31]
        Xinst .PIN1(netA) .PIN2(netB) ...  macro_name
        .ENDS
  - Call: netgen -batch lvs "L.spi SHA256" "S.spi SHA256" setup.tcl rpt -blackbox
"""
import os, sys, subprocess, collections
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from lvs import parse_def, parse_verilog, canon_net_name

DEF_FILE      = os.path.join(HERE, "SHA256_14.3ns.def")
VERILOG_FILE  = os.path.join(HERE, "SHA256_14.3ns_final.v")
OUT_LAYOUT    = os.path.join(HERE, "SHA256_14.3ns.layout.v6.spi")
OUT_SCHEMATIC = os.path.join(HERE, "SHA256_14.3ns.schematic.v6.spi")
REPORT        = os.path.join(HERE, "SHA256.netgen_lvs.v6.report")
from paths import PDK_DIR
SETUP = str(PDK_DIR / "libs.tech" / "netgen" / (PDK_DIR.name + "_setup.tcl"))

# ---------------- filters ----------------
PHYSICAL_HINTS = ("FILL", "TAP", "DIODE", "ANTENNA", "DECAP", "DEF_FILL",
                  "VIA_", "CON_", "WELLTAP", "TIEH", "TIEL", "ANTENNA_")

def is_physical_cell(macro_name, inst_name):
    upm = macro_name.upper()
    upi = inst_name.upper()
    if upm.startswith("VIA_") or upm.endswith("_DEF_FILL"): return True
    if upi.startswith("FILLER_") or upi.startswith("TAP_") or upi.startswith("ANT_"): return True
    if upi.startswith("DECAP_") or upi.startswith("DIODE_") or upi.startswith("WELLTAP_"): return True
    for h in PHYSICAL_HINTS:
        if h in upm: return True
    return False

def augment_pins(pin_dict):
    """Return a new dict with VPWR/VGND/VNB/VPB added (if missing) according to
    the sky130 global-PG convention. Existing entries are NOT overwritten."""
    d = dict(pin_dict)
    if "VPWR" not in d: d["VPWR"] = "VPWR"
    if "VGND" not in d: d["VGND"] = "VGND"
    if "VNB"  not in d: d["VNB"]  = "VGND"
    if "VPB"  not in d: d["VPB"]  = "VPWR"
    return d

# ---------------- SPICE writer (named pin) ----------------
def safe_spice_net(n):
    """SPICE net name — keep as-is but ensure not empty."""
    if not n: return "__empty__"
    return n

def write_named_pin_spice(path, instances, ports, design_name,
                          exclude_physical=True, augment=True):
    lines = []
    lines.append("* LVS V6: named-pin hierarchical SPICE (%s side)" %
                 os.path.basename(path))
    lines.append("* Auto-generated by run_lvs_v6.py from OpenROAD DEF/Verilog")
    lines.append("")

    # Flatten port list (expand bus pins e.g. data[31:0] -> data[0],..data[31])
    flat_ports = []
    for pname, pdir in ports:
        flat_ports.append(pname)
    top_ports_line = " ".join(flat_ports)
    lines.append(".SUBCKT %s  %s" % (design_name, top_ports_line))

    n_inst = 0
    skipped = 0
    for iname, (macro, pin_dict) in sorted(instances.items()):
        if exclude_physical and is_physical_cell(macro, iname):
            skipped += 1
            continue
        pd = augment_pins(pin_dict) if augment else pin_dict
        # Build instance line:  X<inst>  .PIN1(net1) .PIN2(net2) ...  <macro>
        parts = ["X%s" % iname]
        for pin, net in pd.items():
            parts.append(".%s(%s)" % (pin, safe_spice_net(net)))
        parts.append(macro)
        # Keep each line < 500 chars; wrap with + if needed
        # For simplicity: write one line per instance
        line = " ".join(parts)
        if len(line) < 600:
            lines.append(line)
        else:
            # greedy wrap
            acc = parts[0]
            for p in parts[1:]:
                if len(acc) + 1 + len(p) < 500:
                    acc += " " + p
                else:
                    lines.append(acc)
                    acc = "+ " + p
            lines.append(acc)
        n_inst += 1
    lines.append(".ENDS")
    lines.append(".END")
    content = "\n".join(lines) + "\n"
    with open(path, "w") as f:
        f.write(content)
    return n_inst, skipped

# ---------------- main ----------------
def main():
    print("[LVS-V6] Step 1: Parse DEF & Verilog")
    linst, lnet, lport, ldn = parse_def(DEF_FILE)
    sinst, snet, sport, sdn = parse_verilog(VERILOG_FILE)

    # Use layout's port list as the top-level ports (includes 37 pins explicitly).
    # But schematic parser's port list may be [clk,rst,soc,rd,eoc,data]; we
    # should UNIFY to 37-pin (layout) style. Use lport (canonical, matched).
    top_ports = list(lport)
    top_name  = ldn or "SHA256"

    print("[LVS-V6] Step 2: Write layout SPICE (named-pin)")
    ln, ls = write_named_pin_spice(OUT_LAYOUT, linst, top_ports, top_name)
    print("           Layout: %d logic instances (%d physical skipped)" % (ln, ls))

    print("[LVS-V6] Step 3: Write schematic SPICE (named-pin, same port list)")
    sn, ss = write_named_pin_spice(OUT_SCHEMATIC, sinst, top_ports, top_name)
    print("           Schematic: %d logic instances (%d physical skipped)" % (sn, ss))

    print("[LVS-V6] Step 4: Run Netgen LVS (blackbox, named-pin)")
    cmd = [
        "netgen", "-batch", "lvs",
        '"%s %s"' % (OUT_LAYOUT, top_name),
        '"%s %s"' % (OUT_SCHEMATIC, top_name),
        SETUP,
        REPORT,
        "-blackbox"
    ]
    # Need a shell for proper quoting, so wrap
    shell_cmd = " ".join(cmd)
    print("           " + shell_cmd)
    sys.stdout.flush()
    rc = subprocess.call(shell_cmd, shell=True, cwd=HERE)
    print("[LVS-V6] Netgen exit code = %d" % rc)

    # Show summary
    if os.path.exists(REPORT):
        print("\n=== Report Summary (last 40 lines of %s) ===" % REPORT)
        with open(REPORT) as f:
            lines = f.readlines()
        for l in lines[-40:]:
            sys.stdout.write(l)
    else:
        print("(no report file generated)")
    return rc

if __name__ == "__main__":
    sys.exit(main())
