#!/usr/bin/env python3
"""
LVS V6-pos for 15ns flow (split inout: data_in/data_out/data_oe).

Adapted from run_lvs_v6_pos.py — same positional-pin + blackbox approach,
but targets SHA256_15ns.def / SHA256_15ns_final.v (方案 B split interface).

Key approach (proven by v6pos on 14.3ns flow):
  * BOTH sides (layout + schematic) generated by THIS script → perfectly symmetric.
  * Pin order per stdcell: verbatim from sky130_fd_sc_hd.cdl .SUBCKT line.
  * Top-level .SUBCKT SHA256 port list: 70 pins from parse_def
    (clk data_in[0..31] data_out[0..31] data_oe rd rst soc eoc).
  * Physical-only cells stripped on both sides.
  * Supply pins filled with PIN NAME as global net (VPWR/VGND convention).
"""
import os, re, sys, subprocess, collections

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

try:
    from lvs import parse_def, parse_verilog
except ModuleNotFoundError as exc:
    if exc.name != "lvs":
        raise
    sys.exit("Missing flow/lvs.py (not included in this checkout). Restore the upstream parser before running LVS; see REPRODUCE.zh-CN.md.")

from paths import PDK_DIR
SKY130A = str(PDK_DIR)
LIBCDL   = os.path.join(SKY130A, "libs.ref", "sky130_fd_sc_hd", "cdl", "sky130_fd_sc_hd.cdl")
DEF_FILE     = os.path.join(HERE, "SHA256_15ns.def")
VERILOG_FILE = os.path.join(HERE, "SHA256_15ns_final.v")
SETUP        = os.path.join(SKY130A, "libs.tech", "netgen", PDK_DIR.name + "_setup.tcl")

OUT_LAYOUT    = os.path.join(HERE, "SHA256_15ns.layout.v6pos.cdl")
OUT_SCHEMATIC = os.path.join(HERE, "SHA256_15ns.schematic.v6pos.cdl")
REPORT        = os.path.join(HERE, "SHA256_15ns.netgen_lvs.v6pos.report")

PHYSICAL_HINTS = ("FILL", "TAP", "DIODE", "ANTENNA", "DECAP", "DEF_FILL",
                  "VIA_", "CON_", "WELLTAP", "TIEH", "TIEL")

def is_physical(name, macro):
    upm = macro.upper()
    upi = name.upper()
    if upm.startswith("VIA_") or upm.endswith("_DEF_FILL"): return True
    for pref in ("FILLER_", "TAP_", "ANT_", "DECAP_", "DIODE_", "WELLTAP_"):
        if upi.startswith(pref): return True
    for h in PHYSICAL_HINTS:
        if h in upm: return True
    return False

def parse_libcdl(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()
    port_map = {}
    for m in re.finditer(r'^\s*\.SUBCKT\s+(\S+)\s+(.+?)\s*$', text, re.M | re.I):
        master = m.group(1)
        portline = m.group(2).strip()
        ports = []
        for tok in portline.split():
            if tok.startswith("*"): break
            ports.append(tok)
        port_map[master] = ports
    return port_map

def write_cdl(path, side_label, instances, top_ports, top_name, master_ports,
              include_libcdl_path=None):
    port_names = [p for (p, _) in top_ports]
    lines = []
    lines.append("* ==========================================================")
    lines.append(f"* SHA256 15ns LVS V6-pos — {side_label} side (split inout)")
    lines.append(f"* Pin order per stdcell: copied from sky130_fd_sc_hd.cdl")
    lines.append(f"* Top-level ports: {len(port_names)}")
    lines.append("* ==========================================================")
    lines.append("")

    if include_libcdl_path:
        lib_abs = os.path.abspath(include_libcdl_path)
        lib_abs_fwd = lib_abs.replace("\\", "/")
        lines.append(f'.INCLUDE "{lib_abs_fwd}"')
        lines.append("* (stdcell .SUBCKT definitions loaded from canonical lib)")
        lines.append("")

    lines.append(f".SUBCKT {top_name} " + " ".join(port_names))

    written = 0
    skipped = 0
    unknown = collections.Counter()
    supply_fills = collections.Counter()

    for iname in sorted(instances.keys()):
        macro, pin_dict = instances[iname]
        if is_physical(iname, macro):
            skipped += 1
            continue
        if macro not in master_ports:
            unknown[macro] += 1
            raw = [pin_dict.get(k, "__NC__") for k in list(pin_dict.keys())]
            lines.append(f"* [WARN] master {macro} not in libcdl (raw fallback)")
            lines.append(f"X{iname} " + " ".join(raw) + f" {macro}")
            continue
        plist = master_ports[macro]
        out_nets = []
        for pname in plist:
            if pname in pin_dict:
                out_nets.append(pin_dict[pname])
            else:
                if pname == "VNB":
                    out_nets.append("VGND")
                elif pname == "VPB":
                    out_nets.append("VPWR")
                else:
                    out_nets.append(pname)
                supply_fills[f"{macro}::{pname}"] += 1
        lines.append(f"X{iname} " + " ".join(out_nets) + f" {macro}")
        written += 1

    lines.append(f".ENDS {top_name}")
    lines.append(".END")
    with open(path, "w", encoding="utf-8", errors="replace") as f:
        f.write("\n".join(lines) + "\n")
    stats = {"written": written, "skipped": skipped,
             "unknown": dict(unknown.most_common()),
             "top_supply_fills": supply_fills.most_common(10),
             "total_supply_fills": sum(supply_fills.values())}
    return stats

def main():
    print("[V6-pos-15ns] Step 1: build libcdl port map")
    master_ports = parse_libcdl(LIBCDL)
    print(f"              libcdl .SUBCKT entries: {len(master_ports)}")

    print("[V6-pos-15ns] Step 2: Parse DEF (layout) + Verilog (schematic)")
    linst, lnet, lport, ldn = parse_def(DEF_FILE)
    sinst, snet, sport, sdn = parse_verilog(VERILOG_FILE)
    top_name = ldn or sdn or "SHA256"
    print(f"              Layout parsed: {len(linst)} insts, {len(lport)} top ports")
    print(f"              Schem  parsed: {len(sinst)} insts, {len(sport)} top decls")

    top_ports = list(lport)
    print(f"              Unified top port list ({len(top_ports)}):")
    for pn, pd in top_ports:
        print(f"                {pn} [{pd}]")

    print("[V6-pos-15ns] Step 3a: Write layout CDL (positional pin + .INCLUDE libcdl)")
    lst = write_cdl(OUT_LAYOUT, "LAYOUT", linst, top_ports, top_name, master_ports,
                    include_libcdl_path=LIBCDL)
    print(f"              layout: {lst['written']} insts written, "
          f"{lst['skipped']} phy skipped, fills={lst['total_supply_fills']}")
    if lst["unknown"]:
        print(f"              WARNING unknown layout macros: {lst['unknown']}")

    print("[V6-pos-15ns] Step 3b: Write schematic CDL (positional pin + .INCLUDE libcdl)")
    sst = write_cdl(OUT_SCHEMATIC, "SCHEMATIC", sinst, top_ports, top_name,
                    master_ports, include_libcdl_path=LIBCDL)
    print(f"              schematic: {sst['written']} insts written, "
          f"{sst['skipped']} phy skipped, fills={sst['total_supply_fills']}")
    if sst["unknown"]:
        print(f"              WARNING unknown schem macros: {sst['unknown']}")

    print("[V6-pos-15ns] Step 4: Run Netgen LVS -blackbox")
    command = [
        os.environ.get("NETGEN", "netgen"), "-batch", "lvs",
        f"{OUT_LAYOUT} {top_name}", f"{OUT_SCHEMATIC} {top_name}",
        SETUP, REPORT, "-blackbox",
    ]
    print("              CMD: " + repr(command))
    sys.stdout.flush()
    env = os.environ.copy()
    env["MAGIC_EXT_USE_GDS"] = "1"
    rc = subprocess.call(command, cwd=HERE, env=env)
    print(f"[V6-pos-15ns] Netgen exit = {rc}")

    if os.path.exists(REPORT):
        print("\n==== REPORT SUMMARY (tail 60) ====")
        with open(REPORT) as f:
            lines = f.readlines()
        for l in lines[-60:]:
            sys.stdout.write(l)
    else:
        print("(no report produced)")
    return rc

if __name__ == "__main__":
    sys.exit(main())
